package bookstore.model.enums;

public enum SortType {
    // Для книг
    BY_TITLE_ASC, BY_TITLE_DESC,
    BY_AUTHOR_ASC, BY_AUTHOR_DESC,
    BY_PRICE_ASC, BY_PRICE_DESC,
    BY_STATUS_ASC, BY_STATUS_DESC,
    BY_PUBLICATION_DATE_ASC, BY_PUBLICATION_DATE_DESC,
    BY_RECEIVED_DATE_ASC, BY_RECEIVED_DATE_DESC,

    // Для заказов
    BY_ORDER_DATE_ASC, BY_ORDER_DATE_DESC,
    BY_COMPLETION_DATE_ASC, BY_COMPLETION_DATE_DESC,
    BY_STATUS_ORDER_ASC, BY_STATUS_ORDER_DESC,
    BY_TOTAL_PRICE_ASC, BY_TOTAL_PRICE_DESC,

    // Для запросов
    BY_REQUESTS_COUNT_ASC, BY_REQUESTS_COUNT_DESC,
    BY_CUSTOMER_NAME_ASC, BY_CUSTOMER_NAME_DESC
}
